volumes/app/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_view
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("profile/edit/avatar/", views.change_avatar, name="change_avatar"),
    path('profile/wishlist/', views.user_wishlist, name="user_wishlist"),
    path("profile/wishlist/add_remove_product/<int:id>/",
         views.add_remove_wishlist,
         name="add_remove_wishlist"),

    # default django url view
    path("login/", auth_view.LoginView.as_view(
            template_name="accounts/login.html"), name="login"),
    path("logout/", auth_view.LogoutView.as_view(), name="logout"),
    path(
        "password_change/", auth_view.PasswordChangeView.as_view(
            template_name="accounts/password_change_form.html"),
        name="password_change"),
    path(
        "password_change/done/",
        auth_view.PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "password_reset/", auth_view.PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="registration/password_reset_subject.txt",
            success_url=reverse_lazy("accounts:password_reset_done")),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_view.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_view.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete")),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_view.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

volumes/app/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name="cart_detail"),
    path('add/<int:product_id>/', views.cart_add, name="cart_add"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
]

volumes/app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dj_rest_auth.views import PasswordResetConfirmView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    # API urls
    # authentication
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/auth/', include('accounts.api_urls', namespace='api-auth')),
    path('api/v1/auth/password/reset/confirm/<uibd64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    # other app
    path('api/v1/shop/', include('shop.api_urls', namespace='api-shop')),

    # Traditional Django urls
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('cart/', include("cart.urls", namespace="cart")),
    path('orders/', include("orders.urls", namespace="orders")),
    path('coupons/', include("coupons.urls", namespace="coupons")),
    path('payments/', include("payments.urls", namespace="payments")),
    path('reviews/', include("reviews.urls", namespace="reviews")),
    path('', include("shop.urls", namespace="shop")),
]
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)


# API Schema
urlpatterns += [
    # YOUR PATTERNS
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/v1/swagger/',
         SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/v1/schema/redoc/',
         SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

volumes/app/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.index, name="index"),
    path("shop/", views.product_list, name="product_list"),
    path("category/<slug:category_slug>/", views.product_list,
         name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail,
         name="product_detail"),
]

volumes/app/shop/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.translation import gettext as _
from utils.general_model import GeneralModel


class Category(GeneralModel):
    """
    Model representing a category for products.
    """

    name = models.CharField(
        max_length=250,
        verbose_name=_("Name"),)
    slug = models.SlugField(
        max_length=250,
        unique=True,
        verbose_name=_("Slug"),)

    class Meta:
        ordering = ["name",]
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        """
        String representation of the category.
        """

        return self.name

    def get_absolute_url(self):
        """
        Get the absolute URL of the category.
        """

        return reverse('shop:product_list_by_category', args=[self.slug,])


class Product(GeneralModel):
    """
    Model representing a product in the shop.
    """

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="products",
        verbose_name=_("Category"))
    name = models.CharField(
        max_length=250,
        verbose_name=_("Name"),)
    slug = models.SlugField(
        max_length=250,
        unique=True,
        verbose_name=_("Slug"),)
    image = models.ImageField(
        upload_to="products/%Y/%m/%d",
        blank=True,
        null=True,
        verbose_name=_("Image"),)
    description = models.TextField(
        blank=True,
        verbose_name=_("Description"),)
    price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        verbose_name=_("Price"),)
    available = models.BooleanField(
        default=True,
        verbose_name=_("Available"),)
    users_wishlist = models.ManyToManyField(
        get_user_model(),
        related_name="user_wishlist",
        blank=True,)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["id", "slug",]),
            models.Index(fields=["name",]),
            models.Index(fields=["-create_at",]),
        ]

    def __str__(self):
        """
        String representation of the product.
        """

        return self.name

    def get_absolute_url(self):
        """
        Get the absolute URL of the product.
        """

        return reverse('shop:product_detail', args=[self.id, self.slug,])


class Product_Image(GeneralModel):
    image = models.ImageField(
        upload_to="products/%Y/%m/%d",
        verbose_name=_("Image"),)
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="images",
        verbose_name=_("Product"))

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")

    def __str__(self):
        return self.product.name + " Image"

    def get_product_name(self):
        return self.product.name
    get_product_name.short_description = _("Product Name")

volumes/app/shop/views.py
from datetime import timedelta
from django.utils import timezone
from django.shortcuts import (
    render,
    get_object_or_404,
)
from django.db.models import Avg, Count
from cart.forms import CartAddProductForm
from reviews.forms import ReviewForm
from orders.models import OrderItem
from shop.models import (
    Category,
    Product,
)
from website.models import Slider


def index(request):
    slides = Slider.objects.filter(status=True)
    categories = Category.objects.all()
    highest_rate_product = Product.objects.annotate(avg_rate=Avg(
        'reviews__rate')).order_by('-avg_rate')
    if len(highest_rate_product) > 6:
        highest_rate_product = highest_rate_product[:6]

    today = timezone.now().date()
    start_date = today - timedelta(days=today.weekday())
    end_date = start_date + timedelta(days=7)

    best_sellers = OrderItem.objects.filter(order__create_at__range=(
        start_date, end_date)).values('product') \
        .annotate(total_sales=Count('product')) \
        .order_by('-total_sales')

    if len(best_sellers) > 4:
        best_sellers = best_sellers[:4]

    product_ids = [item['product'] for item in best_sellers]
    best_sellers = Product.objects.filter(id__in=product_ids) \
        .annotate(avg_rate=Avg('reviews__rate'),
                  rate_count=Count('reviews__rate'))

    featured_products = Product.objects.annotate(num_users=Count(
        'users_wishlist')).order_by('-num_users')

    if len(featured_products) > 4:
        featured_products = featured_products[:4]

    wishlist_products = []
    if request.user.is_authenticated:
        user = request.user
        wishlist_products = user.user_wishlist.filter(available=True)\
            .values_list('id', flat=True)

    return render(request,
                  "shop/index.html",
                  {"slides": slides,
                   "categories": categories,
                   "highest_rate_product": highest_rate_product,
                   "best_sellers_product": best_sellers,
                   "featured_products": featured_products,
                   "wishlist_products": wishlist_products, })


def product_list(request, category_slug=None):
    """
    View function for displaying a list of products.

    Args:
        request: The HTTP request object.
        category_slug: Optional category slug to filter products by category.

    Returns:
        The rendered template with the list of products.
    """

    category = None
    grid = False
    product_exist = True
    products_description = ""
    categories = Category.objects.all()
    products = Product.objects.filter(available=True,) \
        .annotate(avg_rate=Avg('reviews__rate'),
                  rate_count=Count('reviews__rate'))

    # search query
    if search_q := request.GET.get("q"):
        products = products.filter(name__icontains=search_q)

    wishlist_products = []
    if request.user.is_authenticated:
        user = request.user
        wishlist_products = user.user_wishlist.filter(available=True)\
            .values_list('id', flat=True)

    if len(products) == 0:
        product_exist = False
        products_description = "این فروشگاه محصولی را ثبت نکرده است."

    if category_slug and product_exist:
        category = get_object_or_404(
            Category,
            slug=category_slug,
        )
        products = products.filter(category=category)
        if len(products) == 0:
            product_exist = False
            products_description = "برای این دسته‌بندی محصولی ثبت نشده است."

    # show in grid or list type
    if request.GET.get('style', None) == 'list':
        grid = False
    else:
        grid = True

    cart_product_form = CartAddProductForm(auto_id=False,
                                           initial={"override": True, })

    return render(
        request=request,
        template_name='shop/product/list.html',
        context={
            'category': category,
            'categories': categories,
            'products': products,
            'product_exist': product_exist,
            'products_description': products_description,
            'grid': grid,
            'cart_product_form': cart_product_form,
            'wishlist_products': wishlist_products,
        }
    )


def product_detail(request, id, slug):
    """
    View function for displaying the details of a product.

    Args:
        request: The HTTP request object.
        id: The ID of the product.
        slug: The slug of the product.

    Returns:
        The rendered template with the product details.
    """

    product = get_object_or_404(
        Product,
        id=id,
        slug=slug,
        available=True,
    )
    product_images = product.images.all()

    wishlist_product = []
    if request.user.is_authenticated:
        user = request.user
        wishlist_product = user.user_wishlist.filter(available=True, id=id)

    reviews = product.reviews.filter(status='A')
    try:
        reviews_avg = f"{(sum(reviews.values_list('rate', flat=True)) / len(reviews)):.1f}"
    except ZeroDivisionError:
        reviews_avg = 0

    filled_stars = int(float(reviews_avg))
    unfilled_stars = 5 - filled_stars

    cart_product_form = CartAddProductForm()
    review_form = ReviewForm(auto_id=False,)

    return render(
        request=request,
        template_name='shop/product/detail.html',
        context={
            'product': product,
            'product_images': product_images,
            'cart_product_form': cart_product_form,
            'review_form': review_form,
            'wishlist_product': wishlist_product,
            'reviews': reviews,
            'reviews_avg': reviews_avg,
            'filled_stars': range(filled_stars),
            'unfilled_stars': range(unfilled_stars),
        }
    )

volumes/app/shop/templates/shop/shop-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover, shrink-to-fit=no">
    <meta name="description" content="سوها- Multipurpose Ecommerce Mobile HTML Template">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="theme-color" content="#100DD1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- The above tags *must* come first in the head, any other head content must come *after* these tags-->
    <!-- Title-->
    <title>{% block title %}لیست فروشگاه{% endblock title %}</title>
    <!-- Favicon-->
    <link rel="icon" href="{% static 'front/img/icons/icon-72x72.png' %}">
    <!-- Apple Touch Icon-->
    <link rel="apple-touch-icon" href="{% static 'front/img/icons/icon-96x96.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'front/img/icons/icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="167x167" href="{% static 'front/img/icons/icon-167x167.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'front/img/icons/icon-180x180.png' %}">
    <!-- Stylesheet-->
    <link rel="stylesheet" href="{% static 'front/style.css' %}">
    <link rel="stylesheet" href="{% static 'front/custom.css' %}">
    <!-- Web App Manifest-->
    <link rel="manifest" href="{% static 'front/manifest.json' %}">
</head>
<body>
  
	<!-- Preloader-->
    <div class="preloader" id="preloader">
		<div class="spinner-grow text-secondary" role="status">
		  <div class="sr-only">بارگذاری...</div>
		</div>
	</div>
	
	{% block header %}
	<!-- Header Area-->
    <div class="header-area" id="headerArea">
		<div class="container h-100 d-flex align-items-center justify-content-between">
		  <!-- Back Button-->
		  
		  {% block back-button %}
		  <div class="back-button"><a href="#"><i class="lni lni-arrow-right"></i></a></div>
		  {% endblock back-button %}
		  <!-- Page Title-->
		  <div class="page-heading">
			<h6 class="mb-0">{% block header-title %}لیست فروشگاه{% endblock header-title %}</h6>
		  </div>
			
			{% block header-option %}
			<!-- Navbar Toggler-->
			<div class="suha-navbar-toggler d-flex justify-content-between flex-wrap invisible" id="suhaNavbarToggler"><span></span><span></span><span></span></div>
			{% endblock header-option %}

		</div>
	</div>
	{% if messages %}
		{% for message in messages %}
		<div class="mt-3">
			{% if message.tags == 'info' %}
			<span class="alert alert-primary mt-3" role="alert" style="z-index:1000">
			{% elif message.tags == 'success' %}
			<span class="alert alert-success mt-3" role="alert" style="z-index:1000">
			{% elif message.tags == 'error' %}
			<span class="alert alert-danger mt-3" role="alert" style="z-index:1000">
			{% elif message.tags == 'warning' %}
			<span class="alert alert-warning mt-3" role="alert" style="z-index:1000">
			{% endif %}
				<button type="button" class="close mr-2" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<p class="d-inline">{{ message }}</p>
			</span>
		</div>
		{% endfor %}
	{% endif %}
	{% endblock header %}
		

	
	
	{% comment %} {% block sidebar %}
	<!-- Sidenav Black Overlay-->
    <div class="sidenav-black-overlay"></div>
	<!-- Side Nav Wrapper-->
	<div class="suha-sidenav-wrapper" id="sidenavWrapper">
		<!-- Sidenav Profile-->
		<div class="sidenav-profile">
			<div class="user-profile"><img src="{% static 'front/img/bg-img/9.jpg' %}" alt=""></div>
			<div class="user-info">
			<h6 class="user-name mb-0">نیلوفر</h6>
			<p class="available-balance">حساب شما <span><span class="counter">350000</span></span><span> تومان</span></p>
			</div>
		</div>
		<!-- Sidenav Nav-->
		<ul class="sidenav-nav pl-0">
			<li><a href="#"><i class="lni lni-user"></i>پروفایل من</a></li>
			<li><a href="#"><i class="lni lni-alarm lni-tada-effect"></i>اطلاعیه ها <span class="ml-3 badge badge-warning">3</span></a></li>
			<li class="suha-dropdown-menu"><a href="#"><i class="lni lni-cart"></i>صفحات خرید</a>
			<ul>
				<li><a href="#">- فروشگاه شبکه</a></li>
				<li><a href="#">- لیست فروشگاه</a></li>
				<li><a href="#">- مشخصات محصول</a></li>
				<li><a href="#">- محصولات برجسته</a></li>
				<li><a href="#">- فروش فلش</a></li>
			</ul>
			</li>
			<li><a href="#"><i class="lni lni-empty-file"></i>تمام صفحات</a></li>
			<li class="suha-dropdown-menu"><a href="#"><i class="lni lni-heart"></i>علاقه مندی های من</a>
			<ul>
				<li><a href="#">- شبکه مورد علاقه</a></li>
				<li><a href="#">- لیست دلخواه</a></li>
			</ul>
			</li>
			<li><a href="#"><i class="lni lni-cog"></i>تنظیمات</a></li>
			<li><a href="{% url 'accounts:logout' %}"><i class="lni lni-power-switch"></i>خروج از سیستم</a></li>
		</ul>
		<!-- Go Back Button-->
		<div class="go-home-btn" id="goHomeBtn"><i class="lni lni-arrow-right"></i></div>
	</div>
	{% endblock sidebar %} {% endcomment %}


	{% block content %}

	{% endblock content %}


	<!-- Internet Connection Status-->
    <div class="internet-connection-status" id="internetStatus"></div>
    <!-- Footer Nav-->
	
	{% block footer %}
    <div class="footer-nav-area" id="footerNav">
      <div class="container h-100 px-0">
        <div class="suha-footer-nav h-100">
		  <ul class="nav h-100 d-flex align-items-center justify-content-between pl-0">
			<li class="nav-item active"><a class="nav-link" href="{% url 'shop:index' %}"><i class="lni lni-home"></i>خانه</a></li>
            <li class="nav-item"><a class="nav-link " href="{% url 'shop:product_list' %}">
				<i>
					<?xml version="1.0" encoding="UTF-8"?>
					<svg xmlns="http://www.w3.org/2000/svg" id="Outline" viewBox="0 0 24 24" width="20" height="20"><path d="M24,10a.988.988,0,0,0-.024-.217l-1.3-5.868A4.968,4.968,0,0,0,17.792,0H6.208a4.968,4.968,0,0,0-4.88,3.915L.024,9.783A.988.988,0,0,0,0,10v1a3.984,3.984,0,0,0,1,2.643V19a5.006,5.006,0,0,0,5,5H18a5.006,5.006,0,0,0,5-5V13.643A3.984,3.984,0,0,0,24,11ZM2,10.109l1.28-5.76A2.982,2.982,0,0,1,6.208,2H7V5A1,1,0,0,0,9,5V2h6V5a1,1,0,0,0,2,0V2h.792A2.982,2.982,0,0,1,20.72,4.349L22,10.109V11a2,2,0,0,1-2,2H19a2,2,0,0,1-2-2,1,1,0,0,0-2,0,2,2,0,0,1-2,2H11a2,2,0,0,1-2-2,1,1,0,0,0-2,0,2,2,0,0,1-2,2H4a2,2,0,0,1-2-2ZM18,22H6a3,3,0,0,1-3-3V14.873A3.978,3.978,0,0,0,4,15H5a3.99,3.99,0,0,0,3-1.357A3.99,3.99,0,0,0,11,15h2a3.99,3.99,0,0,0,3-1.357A3.99,3.99,0,0,0,19,15h1a3.978,3.978,0,0,0,1-.127V19A3,3,0,0,1,18,22Z" fill="#747794"/></svg>
				</i>
				</svg>
				فروشگاه</a>
			</li>
            <li class="nav-item">
				{% with cart|length as total_items %}
					{% if total_items > 0 %}
					<span class="badge badge-danger cart-badge">{{ total_items }}</span>
					{% endif %}
				{% endwith %}
				<a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="lni lni-shopping-basket"></i>سبد خرید</a></li>
            <li class="nav-item"><a class="nav-link " href="{% url 'accounts:user_wishlist' %}"><i class="lni lni-heart"></i>علاقمندی‌ها</a></li>
            <li class="nav-item"><a class="nav-link " href="{% url 'accounts:profile' %}"><i class="lni lni-user"></i>پروفایل</a></li>
		  </ul>
        </div>
      </div>
    </div>
	{% endblock footer %}
		
	

	<!-- All JavaScript Files-->
	<script src="{% static 'front/js/jquery.min.js' %}"></script>
	<script src="{% static 'front/js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'front/js/waypoints.min.js' %}"></script>
	<script src="{% static 'front/js/jquery.easing.min.js' %}"></script>
	<script src="{% static 'front/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'front/js/jquery.counterup.min.js' %}"></script>
	<script src="{% static 'front/js/jquery.countdown.min.js' %}"></script>
	<script src="{% static 'front/js/default/jquery.passwordstrength.js' %}"></script>
	<script src="{% static 'front/js/wow.min.js' %}"></script>
	<script src="{% static 'front/js/jarallax.min.js' %}"></script>
	<script src="{% static 'front/js/jarallax-video.min.js' %}"></script>
	<script src="{% static 'front/js/default/dark-mode-switch.js' %}"></script>
	<script src="{% static 'front/js/default/no-internet.js' %}"></script>
	<script src="{% static 'front/js/default/active.js' %}"></script>
	<script src="{% static 'front/js/pwa.js' %}"></script>

	
	{% block domready %}
		
	{% endblock domready %}

	{% block domreadyall %}
	<script>
		// Retrieve the visitedPages array from localStorage or initialize it to an empty array
		var visitedPages = JSON.parse(localStorage.getItem('visitedPages')) || [];

		// Function to update the visited pages array
		function updateVisitedPages() {
		// Add the current page URL to the array
		visitedPages.push(window.location.href);

		// Set the last item of the array as the back button URL
		var backButton = document.querySelector('.back-button a');
		backButton.href = visitedPages[visitedPages.length - 2] || '#'; // If there is no previous page, set the URL to '#'

		// Save the visitedPages array to localStorage
		localStorage.setItem('visitedPages', JSON.stringify(visitedPages));
		}

		// Call the updateVisitedPages function when the page loads
		updateVisitedPages();

		// Add an event listener to the back button
		var backButton = document.querySelector('.back-button a');
		backButton.addEventListener('click', function() {
		visitedPages.pop(); // Remove the last item from the array

		// Update the localStorage with the modified visitedPages array
		localStorage.setItem('visitedPages', JSON.stringify(visitedPages));
		});
	</script>
	{% endblock domreadyall %}

</body>
</html>