volumes/app/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_view
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("profile/edit/avatar/", views.change_avatar, name="change_avatar"),
    path('profile/wishlist/', views.user_wishlist, name="user_wishlist"),
    path("profile/wishlist/add_remove_product/<int:id>/",
         views.add_remove_wishlist,
         name="add_remove_wishlist"),

    # default django url view
    path("login/", auth_view.LoginView.as_view(
            template_name="accounts/login.html"), name="login"),
    path("logout/", auth_view.LogoutView.as_view(), name="logout"),
    path(
        "password_change/", auth_view.PasswordChangeView.as_view(
            template_name="accounts/password_change_form.html"),
        name="password_change"),
    path(
        "password_change/done/",
        auth_view.PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "password_reset/", auth_view.PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="registration/password_reset_subject.txt",
            success_url=reverse_lazy("accounts:password_reset_done")),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_view.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_view.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete")),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_view.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

volumes/app/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name="cart_detail"),
    path('add/<int:product_id>/', views.cart_add, name="cart_add"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
]

volumes/app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dj_rest_auth.views import PasswordResetConfirmView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    # API urls
    # authentication
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/auth/', include('accounts.api_urls', namespace='api-auth')),
    path('api/v1/auth/password/reset/confirm/<uibd64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    # other app
    path('api/v1/shop/', include('shop.api_urls', namespace='api-shop')),

    # Traditional Django urls
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('cart/', include("cart.urls", namespace="cart")),
    path('orders/', include("orders.urls", namespace="orders")),
    path('coupons/', include("coupons.urls", namespace="coupons")),
    path('payments/', include("payments.urls", namespace="payments")),
    path('reviews/', include("reviews.urls", namespace="reviews")),
    path('', include("shop.urls", namespace="shop")),
]
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)


# API Schema
urlpatterns += [
    # YOUR PATTERNS
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/v1/swagger/',
         SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/v1/schema/redoc/',
         SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

volumes/app/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("", views.orders_list, name="orders_list"),
    path("create/", views.order_create, name="order_create"),
    path("<int:id>/", views.order_detail, name="order_detail"),
    path("<int:order_id>/payment/", views.send_to_payment,
         name="order_payment")
]

volumes/app/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.index, name="index"),
    path("shop/", views.product_list, name="product_list"),
    path("category/<slug:category_slug>/", views.product_list,
         name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail,
         name="product_detail"),
]

volumes/app/accounts/models.py
import os
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator
from django.utils.translation import gettext as _
from utils.general_model import GeneralModel
from accounts.managers import CustomUserManager


def get_file_path(instance, filename):
    """
    Function to generate a unique file path for user avatar.

    Args:
        instance: The instance of the user model.
        filename (str): The original filename of the uploaded file.

    Returns:
        str: The unique file path for the user avatar.
    """

    ext = filename.split('.')[-1]
    filename = '%s.%s' % (uuid.uuid4(), ext)
    return os.path.join('users/', filename)


class CustomUser(AbstractUser, GeneralModel):
    """
    Custom user model for the accounts app.

    This model extends the AbstractUser class provided by Django and adds
    additional fields.
    """

    first_name = None
    last_name = None
    full_name = models.CharField(
        max_length=128,
        verbose_name=_("Full name"),
    )
    nick_name = models.CharField(
        max_length=128,
        verbose_name=_("Nick name"),
    )
    email = models.EmailField(
        unique=True,
        verbose_name=_("Email address"),
    )
    phone = models.CharField(
        max_length=13,
        validators=[MinLengthValidator(10)],
        blank=True,
        null=True,
        verbose_name=_("Phone"),
    )
    address = models.CharField(
        max_length=512,
        blank=True,
        null=True,
        verbose_name=_("Address"),
    )
    avatar = models.ImageField(
        upload_to=get_file_path,
        null=True,
        blank=True,
        verbose_name=_("Image profile"),
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        """
        Override the save method to set the username as the email address.

        This method automatically sets the value of the username field as
        the value of the email field when a CustomUser instance is saved.

        Args:
            *args: Additional positional arguments passed to the save method.
            **kwargs: Additional keyword arguments passed to the save method.
        """
        self.username = self.email
        super().save(*args, **kwargs)

    def __str__(self):
        """
        Get a string representation of the user.

        Returns:
            str: The email address of the user.
        """

        return self.email

volumes/app/accounts/forms.py
from django import forms
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import password_validation
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
)
from django.core.exceptions import ValidationError
from accounts.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """
    Form for creating a new custom user.

    This form extends the UserCreationForm provided by Django and adds
    additional validation for the password field.

    Attributes:
        password2: Field to confirm the password and set to None to remove
    """

    password2 = None

    class Meta:
        model = CustomUser
        fields = ("email", "full_name")

    def _post_clean(self):
        """
        Perform additional validation after the form is cleaned.

        This method validates the password field using the password_validation
        module.
        If any validation error occurs, it adds the error to the 'password1'
        field.
        """

        super()._post_clean()

        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get('password1')
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error('password1', error)


class CustomUserChangeForm(UserChangeForm):
    """
    Form for updating an existing custom user.

    This form extends the UserChangeForm provided by Django.

    Attributes:
        model: The custom user model to be used.
        fields: The fields to be displayed in the form.
    """

    class Meta:
        model = CustomUser
        fields = ("email",)


class ProfileForm(forms.ModelForm):
    """
    Form for updating the user profile.

    This form is used to update fields such as nick_name, full_name, phone,
    email, address, and avatar.

    Attributes:
        model: The custom user model to be used.
        fields: The fields to be displayed in the form.
    """

    class Meta:
        model = CustomUser
        fields = ("nick_name", "full_name", "phone",
                  "email", "address",)


class ChangeAvatarForm(forms.ModelForm):
    avatar = forms.FileField(widget=forms.FileInput())

    class Meta:
        model = CustomUser
        fields = ("avatar",)


class GroupAdminForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(GroupAdminForm, self).__init__(*args, **kwargs)
        # Get the ContentType for the 'allauth' and 'socialaccount' apps
        excluded_content_types = ContentType.objects.filter(
            app_label__in=['allauth', 'socialaccount']
        )
        # Get the ids of the associated Permissions
        excluded_permissions = Permission.objects.filter(
            content_type__in=excluded_content_types
        ).values_list('id', flat=True)
        # Exclude the permissions from the queryset
        self.fields['permissions'].queryset = \
            self.fields['permissions'].queryset.exclude(
                id__in=excluded_permissions
            )

volumes/app/accounts/views.py
from django.http import (
    HttpResponseRedirect,
    JsonResponse,
)
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from django.contrib.auth import (
    login,
    authenticate,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from accounts.models import CustomUser
from accounts.forms import (
    CustomUserCreationForm,
    ProfileForm,
    ChangeAvatarForm,
)
from shop.models import Product
from cart.forms import CartAddProductForm


User = get_user_model()


def signup(request):
    """
    View function for user registration/signup.
    """

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            full_name = form.cleaned_data.get("full_name")
            raw_password = form.cleaned_data.get("password1")
            form = form.save(commit=False)
            form.username = email
            form.nick_name = full_name
            form.save()
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect("shop:product_list")
    else:
        form = CustomUserCreationForm()
    return render(request,
                  "accounts/signup.html",
                  {"form": form, })


@login_required
def profile(request):
    """
    View function to display user profile page.
    """

    return render(request,
                  "accounts/profile.html",)


@login_required
def edit_profile(request):
    """
    View function for editing user profile page.
    """

    user = CustomUser.objects.get(id=request.user.id)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            if "email" in form.changed_data:
                form.username = form.cleaned_data.get("email")
            form.save()
            return redirect("accounts:profile")
    else:
        form = ProfileForm(instance=user)
        change_avatar_form = ChangeAvatarForm(instance=user)

    return render(request,
                  "accounts/edit_profile.html",
                  {"form": form,
                   "change_avatar_form": change_avatar_form, })


@login_required
def change_avatar(request):
    """
    View function to handle the change of user avatar.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        JsonResponse: A JSON response indicating the success status and the
        new avatar URL.

    Raises:
        CustomUser.DoesNotExist: If the user does not exist.

    Notes:
        - This function is decorated with `@login_required` to ensure that the
          user is authenticated.
        - The function expects a POST request with a file upload field
          containing the new avatar image.

    """
    user = CustomUser.objects.get(id=request.user.id)
    if request.method == "POST" and request.FILES:
        form = ChangeAvatarForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            user = CustomUser.objects.get(id=request.user.id)
            avatar_url = user.avatar.url
            return JsonResponse({'success': True,
                                 'avatar_url': avatar_url, })

    return JsonResponse({'success': False})


@login_required
def add_remove_wishlist(request, id):
    product = get_object_or_404(Product, id=id)
    if product.users_wishlist.filter(id=request.user.id).exists():
        product.users_wishlist.remove(request.user)
    else:
        product.users_wishlist.add(request.user)
    try:
        return HttpResponseRedirect(request.META['HTTP_REFERER'])
    except KeyError:
        return redirect('/')


@login_required
def user_wishlist(request):
    user = request.user
    grid = False
    product_exist = True
    products_description = ""

    # show in grid or list type
    if request.GET.get('style', None) == 'list':
        grid = False
    else:
        grid = True

    products = user.user_wishlist.filter(available=True,)

    if len(products) == 0:
        product_exist = False
        products_description = "شما محصولی را به لیست علاقمندی‌های خود \
                اضافه نکرده‌اید!"

    cart_product_form = CartAddProductForm(auto_id=False,
                                           initial={"override": True, })

    return render(
        request=request,
        template_name='accounts/wishlist.html',
        context={
            'products': products,
            'grid': grid,
            'product_exist': product_exist,
            'products_description': products_description,
            'cart_product_form': cart_product_form,
        }
    )

volumes/app/accounts/templates/accounts/edit_profile.html
{% extends 'shop/shop-base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}
ویرایش نمایه
{% endblock title %}


{% block header %}
<!-- Header Area-->
<div class="header-area" id="headerArea">
	<div class="container h-100 d-flex align-items-center justify-content-between">
	  <!-- Back Button-->
	  <div class="back-button"><a href="{% url 'accounts:profile' %}"><i class="lni lni-arrow-right"></i></a></div>
	  <!-- Page Title-->
	  <div class="page-heading">
		<h6 class="mb-0">ویرایش نمایه</h6>
	  </div>
	  {% block header-option %}
	  <!-- Navbar Toggler-->
	  <div class="suha-navbar-toggler d-flex justify-content-between flex-wrap invisible" id="suhaNavbarToggler"><span></span><span></span><span></span></div>
	  {% endblock header-option %}
	</div>
  </div>
{% endblock header %}


{% block content %}
<div class="page-content-wrapper">
	<div class="container">
	  <!-- Profile Wrapper-->
	  <div class="profile-wrapper-area py-3">
		{% if form.non_field_errors %}
			<div class="alert alert-danger">
				{% for error in form.non_field_errors %}
				{{ error }}
				{% endfor %}
			</div>
		{% endif %}
		<!-- User Information-->
		<div class="card user-info-card">
			<div class="card-body p-4 d-flex align-items-center">
				<div class="user-profile mr-3">
					{% if user.avatar %}
					<img id="avatar" src="{{ user.avatar.url }}" alt="">
					{% else %}
					<img id="avatar" src="{% static 'front/img/user-profile.png' %}" alt="">
					{% endif %}
					<form method="post" action="{% url 'accounts:change_avatar' %}" id="change_avatar_form" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="change-user-thumb">
							{% render_field change_avatar_form.avatar class+="form-control-file" %}
							<button><i class="lni lni-pencil"></i></button>
						</div>
					</form>
				</div>
				<div class="user-info">
				{% comment %} <p class="mb-0 text-white">design-world @</p> {% endcomment %}
				<h5 class="mb-0">{% if request.user.nick_name %}{{ request.user.nick_name }}{% else %} - {% endif %}</h5>
				</div>
			</div>
			<div id="success-avatar-alert" class="alert alert-success position-fixed m-2 d-none" style="z-index:9999;" role="alert">
				<button id="success-close-alert" type="button" class="close mr-2" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<p class="d-inline">عکس پروفایل شما با موفقیت ویرایش شد!</p>
			</div>
			<div id="fail-avatar-alert" class="alert alert-danger position-fixed m-2 d-none" style="z-index:9999;" role="alert">
				<button id="fail-close-alert" type="button" class="close mr-2" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<p class="d-inline">ویرایش عکس پروفایل شما با خطا مواجه شد!</p>
			</div>
		</div>
		<!-- User Meta Data-->
		<form method="post">
			<div class="card user-data-card">
			<div class="card-body">
				<div class="mb-3">
					<div class="title mb-2"><i class="lni lni-user"></i><span>نام نمایشی</span></div>
					{% render_field form.nick_name class+="form-control" placeholder="ندا" %}
					{% for error in form.nick_name.errors %}
						<div class="invalid-feedback d-block">
							{{ error }}
						</div>
					{% endfor %}
				</div>
				<div class="mb-3">
					<div class="title mb-2"><i class="lni lni-user"></i><span>نام و نام خانوادگی</span></div>
					{% render_field form.full_name class+="form-control" placeholder="ندا رضوانی" %}
					{% for error in form.full_name.errors %}
						<div class="invalid-feedback d-block">
							{{ error }}
						</div>
					{% endfor %}
				</div>
				<div class="mb-3">
					<div class="title mb-2"><i class="lni lni-phone"></i><span>تلفن</span></div>
					{% render_field form.phone class+="form-control" placeholder="09123456789" %}
					{% for error in form.phone.errors %}
						<div class="invalid-feedback d-block">
							{{ error }}
						</div>
					{% endfor %}
				</div>
				<div class="mb-3">
					<div class="title mb-2"><i class="lni lni-envelope"></i><span>آدرس ایمیل</span></div>
					{% render_field form.email class+="form-control" placeholder="care@example.com" %}
					{% if form.email.errors %}
					<div class="invalid-feedback d-block">
						{{ form.email.errors }}
					</div>
					{% endif %}
				</div>
				<div class="mb-3">
					<div class="title mb-2"><i class="lni lni-map-marker"></i><span>آدرس حمل و نقل</span></div>
					{% render_field form.address class+="form-control" placeholder="تهران - ونک" %}
					{% for error in form.address.errors %}
						<div class="invalid-feedback d-block">
							{{ error }}
						</div>
					{% endfor %}
				</div>
				{% csrf_token %}
				<button class="btn btn-success w-100" type="submit">ذخیره همه تغییرات</button>
			</div>
			</div>
		</form>
	  </div>
	</div>
</div>
{% endblock content %}


{% block domready %}
<script>
$('#id_avatar').change(function(){
	var form = $('#change_avatar_form')[0];
    var formData = new FormData(form);

    $.ajax({
      url: '{% url "accounts:change_avatar" %}',
      type: 'POST',
      data: formData,
      processData: false,
      contentType: false,
      success: function(data) {
		if (data.success) {
			$('#avatar').attr('src', data.avatar_url);
			$('#success-avatar-alert').removeClass('d-none');
		}
		else {
			$('#fail-avatar-alert').removeClass('d-none');
		}
      },
      error: function(error) {
        $('#fail-avatar-alert').removeClass('d-none');
      }
    });
});

$('#success-close-alert').click(function() {
    $('#success-avatar-alert').addClass('d-none');
});

$('#fail-close-alert').click(function() {
    $('#fail-avatar-alert').addClass('d-none');
});
</script>
{% endblock domready %}

volumes/app/accounts/templates/accounts/profile.html
{% extends 'shop/shop-base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}
پروفایل
{% endblock title %}


{% block header %}
<!-- Header Area-->
<div class="header-area" id="headerArea">
	<div class="container h-100 d-flex align-items-center justify-content-between">
	  <!-- Logo Wrapper-->
	  <div class="logo-wrapper"><a href="#"><img src="{% static 'front/img/core-img/logo-small.png' %}" alt=""></a></div>
	  <!-- Search Form-->
	  <div class="top-search-form">
		<form action="{% url 'shop:product_list' %}" method="">
		  <input name="q" class="form-control" type="search" placeholder="کلمه کلیدی خود را وارد کنید">
		  <button type="submit"><i class="fa fa-search"></i></button>
		</form>
	  </div>
	  {% block header-option %}
	  <!-- Navbar Toggler-->
	  <div class="suha-navbar-toggler d-flex justify-content-between flex-wrap invisible" id="suhaNavbarToggler"><span></span><span></span><span></span></div>
	  {% endblock header-option %}
	</div>
</div>
{% endblock header %}


{% block content %}
<div class="page-content-wrapper">
	<div class="container">
	  <!-- Profile Wrapper-->
	  <div class="profile-wrapper-area py-3">
		<!-- User Information-->
		<div class="card user-info-card">
		  <div class="card-body p-4 d-flex align-items-center">
			<div class="user-profile mr-3">
				{% if user.avatar %}
				<img src="{{ user.avatar.url }}" alt="">
				{% else %}
				<img src="{% static 'front/img/user-profile.png' %}" alt="">
				{% endif %}
			</div>
			<div class="user-info">
			  {% comment %} <p class="mb-0 text-white">design-world @</p> {% endcomment %}
			  <h5 class="mb-0">{% if request.user.nick_name %}{{ request.user.nick_name }}{% else %} - {% endif %}</h5>
			</div>
		  </div>
		</div>
		<!-- User Meta Data-->
		<div class="card user-data-card">
		  <div class="card-body">
			<div class="single-profile-data d-flex align-items-center justify-content-between">
			  <div class="title d-flex align-items-center"><i class="lni lni-user"></i><span>نام نمایشی</span></div>
			  <div class="data-content">{% if request.user.nick_name %}{{ request.user.nick_name }}{% else %} - {% endif %}</div>
			</div>
			<div class="single-profile-data d-flex align-items-center justify-content-between">
			  <div class="title d-flex align-items-center"><i class="lni lni-user"></i><span>نام و نام خانوادگی</span></div>
			  <div class="data-content">{% if request.user.full_name %}{{ request.user.full_name }}{% else %} - {% endif %}</div>
			</div>
			<div class="single-profile-data d-flex align-items-center justify-content-between">
			  <div class="title d-flex align-items-center"><i class="lni lni-phone"></i><span>تلفن</span></div>
			  <div class="data-content">{% if request.user.phone %}{{ request.user.phone }}{% else %} - {% endif %}</div>
			</div>
			<div class="single-profile-data d-flex align-items-center justify-content-between">
			  <div class="title d-flex align-items-center"><i class="lni lni-envelope"></i><span>آدرس ایمیل</span></div>
			  <div class="data-content">{% if request.user.email %}{{ request.user.email }}{% else %} - {% endif %}</div>
			</div>
			<div class="single-profile-data d-flex align-items-center justify-content-between">
			  <div class="title d-flex align-items-center"><i class="lni lni-map-marker"></i><span>آدرس:</span></div>
			  <div class="data-content">{% if request.user.address %}{{ request.user.address }}{% else %} - {% endif %}</div>
			</div>
			<div class="single-profile-data d-flex align-items-center justify-content-between">
			  <div class="title d-flex align-items-center"><i class="lni lni-star"></i><span>سفارش من</span></div>
			  <div class="data-content"><a class="btn btn-danger btn-sm" href="{% url 'orders:orders_list' %}">نمایش</a></div>
			</div>
		  </div>
		</div>
		<!-- Edit Profile-->
		<div class="edit-profile-btn mt-3"><a class="btn btn-info w-100" href="{% url 'accounts:edit_profile' %}"><i class="lni lni-pencil mr-2"></i>ویرایش نمایه</a></div>
		<div class="edit-profile-btn mt-3"><a class="btn btn-primary w-100" href="{% url 'accounts:password_change' %}"><i class="lni lni-key mr-2"></i>تغییر رمز عبور</a></div>
		{% if user.is_superuser or user.is_staff %}
		<div class="edit-profile-btn mt-3"><a class="btn btn-secondary w-100" href="{% url 'admin:index' %}"><i class="lni lni-key mr-2"></i>ورود به پنل مدیریت</a></div>
		{% endif %}
		<div class="edit-profile-btn mt-3"><a class="btn btn-danger w-100" href="{% url 'accounts:logout' %}"><i class="lni lni-exit mr-2"></i>خروج از حساب کاربری</a></div>
	  </div>
	</div>
</div>
{% endblock content %}

volumes/app/accounts/templates/accounts/signup.html
{% extends 'shop/shop-base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}
ثبت نام
{% endblock title %}


{% block header %}
{% endblock header %}


{% block sidebar %}
{% endblock sidebar %}

{% block content %}
<!-- Login Wrapper Area-->
<div class="login-wrapper d-flex align-items-center justify-content-center text-center">
	<!-- Background Shape-->
	<div class="background-shape"></div>
	<div class="container">
	  <div class="row justify-content-center">
		<div class="col-12 col-sm-9 col-md-7 col-lg-6 col-xl-5"><img class="big-logo" src="{% static 'front/img/core-img/logo-white.png' %}" alt="">
		  <!-- Register Form-->
		  <div class="register-form mt-5 px-4">
			{% if form.non_field_errors %}
				<div class="alert alert-danger">
				  {% for error in form.non_field_errors %}
					{{ error }}
				  {% endfor %}
				</div>
			{% endif %}
			<form method="post">
			  <div class="form-group text-left mb-4"><span>نام کامل شما</span>
				<label for="id_full_name"><i class="lni lni-user"></i></label>
				{% render_field form.full_name class+="form-control" placeholder="جهان طراحی" autofocus="autofocus" %}
				{% if form.full_name.errors %}
				<div class="invalid-feedback d-block">
					{{ form.full_name.errors }}
				</div>
				{% endif %}
			  </div>
			  <div class="form-group text-left mb-4"><span>پست الکترونیک</span>
				<label for="id_email"><i class="lni lni-envelope"></i></label>
				{% render_field form.email class+="form-control" placeholder="help@example.com" %}
				{% if form.email.errors %}
				<div class="invalid-feedback d-block">
					{{ form.email.errors }}
				</div>
				{% endif %}
			  </div>
			  <div class="form-group text-left mb-4"><span>کلمه عبور</span>
				<label for="id_password1"><i class="lni lni-lock"></i></label>
				{% render_field form.password1 class+="input-psswd form-control" placeholder="********************" %}
				{% if form.password1.errors %}
				<div class="invalid-feedback d-block">
					{{ form.password1.errors }}
				</div>
				{% endif %}
			  </div>
			  {% csrf_token %}
			  <button class="btn btn-success btn-lg w-100" type="submit">ثبت نام</button>
			</form>
		  </div>
		  <!-- Login Meta-->
		  <div class="login-meta-data">
			{% if request.GET.next %}
			<p class="mt-3 mb-0">قبلاً حساب دارید؟ <a class="ml-1" href="{% url 'accounts:login' %}?next={{ request.GET.next }}">ورود</a></p>
			{% else %}
			<p class="mt-3 mb-0">قبلاً حساب دارید؟ <a class="ml-1" href="{% url 'accounts:login' %}">ورود</a></p>
			{% endif %}
		  </div>
		</div>
	  </div>
	</div>
</div>
{% endblock content %}


{% block footer %}
	
{% endblock footer %}