volumes/app/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_view
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("profile/edit/avatar/", views.change_avatar, name="change_avatar"),
    path('profile/wishlist/', views.user_wishlist, name="user_wishlist"),
    path("profile/wishlist/add_remove_product/<int:id>/",
         views.add_remove_wishlist,
         name="add_remove_wishlist"),

    # default django url view
    path("login/", auth_view.LoginView.as_view(
            template_name="accounts/login.html"), name="login"),
    path("logout/", auth_view.LogoutView.as_view(), name="logout"),
    path(
        "password_change/", auth_view.PasswordChangeView.as_view(
            template_name="accounts/password_change_form.html"),
        name="password_change"),
    path(
        "password_change/done/",
        auth_view.PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "password_reset/", auth_view.PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="registration/password_reset_subject.txt",
            success_url=reverse_lazy("accounts:password_reset_done")),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_view.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_view.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete")),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_view.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

volumes/app/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name="cart_detail"),
    path('add/<int:product_id>/', views.cart_add, name="cart_add"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
]

volumes/app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dj_rest_auth.views import PasswordResetConfirmView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    # API urls
    # authentication
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/auth/', include('accounts.api_urls', namespace='api-auth')),
    path('api/v1/auth/password/reset/confirm/<uibd64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    # other app
    path('api/v1/shop/', include('shop.api_urls', namespace='api-shop')),

    # Traditional Django urls
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('cart/', include("cart.urls", namespace="cart")),
    path('orders/', include("orders.urls", namespace="orders")),
    path('coupons/', include("coupons.urls", namespace="coupons")),
    path('payments/', include("payments.urls", namespace="payments")),
    path('reviews/', include("reviews.urls", namespace="reviews")),
    path('', include("shop.urls", namespace="shop")),
]
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)


# API Schema
urlpatterns += [
    # YOUR PATTERNS
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/v1/swagger/',
         SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/v1/schema/redoc/',
         SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

volumes/app/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("<int:id>/create/", views.create_review,
         name="create_review"),
]

volumes/app/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.index, name="index"),
    path("shop/", views.product_list, name="product_list"),
    path("category/<slug:category_slug>/", views.product_list,
         name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail,
         name="product_detail"),
]

volumes/app/shop/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.translation import gettext as _
from utils.general_model import GeneralModel


class Category(GeneralModel):
    """
    Model representing a category for products.
    """

    name = models.CharField(
        max_length=250,
        verbose_name=_("Name"),)
    slug = models.SlugField(
        max_length=250,
        unique=True,
        verbose_name=_("Slug"),)

    class Meta:
        ordering = ["name",]
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        """
        String representation of the category.
        """

        return self.name

    def get_absolute_url(self):
        """
        Get the absolute URL of the category.
        """

        return reverse('shop:product_list_by_category', args=[self.slug,])


class Product(GeneralModel):
    """
    Model representing a product in the shop.
    """

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="products",
        verbose_name=_("Category"))
    name = models.CharField(
        max_length=250,
        verbose_name=_("Name"),)
    slug = models.SlugField(
        max_length=250,
        unique=True,
        verbose_name=_("Slug"),)
    image = models.ImageField(
        upload_to="products/%Y/%m/%d",
        blank=True,
        null=True,
        verbose_name=_("Image"),)
    description = models.TextField(
        blank=True,
        verbose_name=_("Description"),)
    price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        verbose_name=_("Price"),)
    available = models.BooleanField(
        default=True,
        verbose_name=_("Available"),)
    users_wishlist = models.ManyToManyField(
        get_user_model(),
        related_name="user_wishlist",
        blank=True,)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["id", "slug",]),
            models.Index(fields=["name",]),
            models.Index(fields=["-create_at",]),
        ]

    def __str__(self):
        """
        String representation of the product.
        """

        return self.name

    def get_absolute_url(self):
        """
        Get the absolute URL of the product.
        """

        return reverse('shop:product_detail', args=[self.id, self.slug,])


class Product_Image(GeneralModel):
    image = models.ImageField(
        upload_to="products/%Y/%m/%d",
        verbose_name=_("Image"),)
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="images",
        verbose_name=_("Product"))

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")

    def __str__(self):
        return self.product.name + " Image"

    def get_product_name(self):
        return self.product.name
    get_product_name.short_description = _("Product Name")

volumes/app/shop/views.py
from datetime import timedelta
from django.utils import timezone
from django.shortcuts import (
    render,
    get_object_or_404,
)
from django.db.models import Avg, Count
from cart.forms import CartAddProductForm
from reviews.forms import ReviewForm
from orders.models import OrderItem
from shop.models import (
    Category,
    Product,
)
from website.models import Slider


def index(request):
    slides = Slider.objects.filter(status=True)
    categories = Category.objects.all()
    highest_rate_product = Product.objects.annotate(avg_rate=Avg(
        'reviews__rate')).order_by('-avg_rate')
    if len(highest_rate_product) > 6:
        highest_rate_product = highest_rate_product[:6]

    today = timezone.now().date()
    start_date = today - timedelta(days=today.weekday())
    end_date = start_date + timedelta(days=7)

    best_sellers = OrderItem.objects.filter(order__create_at__range=(
        start_date, end_date)).values('product') \
        .annotate(total_sales=Count('product')) \
        .order_by('-total_sales')

    if len(best_sellers) > 4:
        best_sellers = best_sellers[:4]

    product_ids = [item['product'] for item in best_sellers]
    best_sellers = Product.objects.filter(id__in=product_ids) \
        .annotate(avg_rate=Avg('reviews__rate'),
                  rate_count=Count('reviews__rate'))

    featured_products = Product.objects.annotate(num_users=Count(
        'users_wishlist')).order_by('-num_users')

    if len(featured_products) > 4:
        featured_products = featured_products[:4]

    wishlist_products = []
    if request.user.is_authenticated:
        user = request.user
        wishlist_products = user.user_wishlist.filter(available=True)\
            .values_list('id', flat=True)

    return render(request,
                  "shop/index.html",
                  {"slides": slides,
                   "categories": categories,
                   "highest_rate_product": highest_rate_product,
                   "best_sellers_product": best_sellers,
                   "featured_products": featured_products,
                   "wishlist_products": wishlist_products, })


def product_list(request, category_slug=None):
    """
    View function for displaying a list of products.

    Args:
        request: The HTTP request object.
        category_slug: Optional category slug to filter products by category.

    Returns:
        The rendered template with the list of products.
    """

    category = None
    grid = False
    product_exist = True
    products_description = ""
    categories = Category.objects.all()
    products = Product.objects.filter(available=True,) \
        .annotate(avg_rate=Avg('reviews__rate'),
                  rate_count=Count('reviews__rate'))

    # search query
    if search_q := request.GET.get("q"):
        products = products.filter(name__icontains=search_q)

    wishlist_products = []
    if request.user.is_authenticated:
        user = request.user
        wishlist_products = user.user_wishlist.filter(available=True)\
            .values_list('id', flat=True)

    if len(products) == 0:
        product_exist = False
        products_description = "این فروشگاه محصولی را ثبت نکرده است."

    if category_slug and product_exist:
        category = get_object_or_404(
            Category,
            slug=category_slug,
        )
        products = products.filter(category=category)
        if len(products) == 0:
            product_exist = False
            products_description = "برای این دسته‌بندی محصولی ثبت نشده است."

    # show in grid or list type
    if request.GET.get('style', None) == 'list':
        grid = False
    else:
        grid = True

    cart_product_form = CartAddProductForm(auto_id=False,
                                           initial={"override": True, })

    return render(
        request=request,
        template_name='shop/product/list.html',
        context={
            'category': category,
            'categories': categories,
            'products': products,
            'product_exist': product_exist,
            'products_description': products_description,
            'grid': grid,
            'cart_product_form': cart_product_form,
            'wishlist_products': wishlist_products,
        }
    )


def product_detail(request, id, slug):
    """
    View function for displaying the details of a product.

    Args:
        request: The HTTP request object.
        id: The ID of the product.
        slug: The slug of the product.

    Returns:
        The rendered template with the product details.
    """

    product = get_object_or_404(
        Product,
        id=id,
        slug=slug,
        available=True,
    )
    product_images = product.images.all()

    wishlist_product = []
    if request.user.is_authenticated:
        user = request.user
        wishlist_product = user.user_wishlist.filter(available=True, id=id)

    reviews = product.reviews.filter(status='A')
    try:
        reviews_avg = f"{(sum(reviews.values_list('rate', flat=True)) / len(reviews)):.1f}"
    except ZeroDivisionError:
        reviews_avg = 0

    filled_stars = int(float(reviews_avg))
    unfilled_stars = 5 - filled_stars

    cart_product_form = CartAddProductForm()
    review_form = ReviewForm(auto_id=False,)

    return render(
        request=request,
        template_name='shop/product/detail.html',
        context={
            'product': product,
            'product_images': product_images,
            'cart_product_form': cart_product_form,
            'review_form': review_form,
            'wishlist_product': wishlist_product,
            'reviews': reviews,
            'reviews_avg': reviews_avg,
            'filled_stars': range(filled_stars),
            'unfilled_stars': range(unfilled_stars),
        }
    )

volumes/app/shop/templates/shop/product/detail.html
{% extends 'shop/shop-base.html' %}
{% load static %}
{% load humanize %}
{% load rate_utils %}
{% load jalali_tags %}

{% block title %}
{% block header-title %}
مشخصات محصول
{% endblock header-title %}
{% endblock title %}

{% block content %}
<div class="page-content-wrapper">
<!-- Product Slides-->
<div class="product-slides owl-carousel">
	<!-- Single Hero Slide-->
	{% if not product.image and not product_images %}
		<div class="single-product-slide" style="background-image: url({% static 'front/img/nopic.jpg' %})"></div>
	{% else %}
		{% if product.image %}<div class="single-product-slide" style="background-image: url({{ product.image.url }})"></div>{% endif %}

		{% if product_images %}
			{% for images in product_images %}
			<div class="single-product-slide" style="background-image: url({{ images.image.url }})"></div>
			{% endfor %}
		{% endif %}
	{% endif %}
</div>
<div class="product-description pb-3">
	<!-- Product Title & Meta Data-->
	<div class="product-title-meta-data bg-white mb-3 py-3">
	<div class="container d-flex justify-content-between">
		<div class="p-title-price">
		<h6 class="mb-1">{{ prpduct.name }}</h6>
		<p class="sale-price mb-0">{{ product.price|floatformat:-2|intcomma }} تومان</p>
		</div>
		<div class="p-wishlist-share"><a href="{% url 'accounts:add_remove_wishlist' product.id %}">{% if user.is_authenticated and wishlist_product %}<i class="lni lni-heart-filled"></i>{% else %}<i class="lni lni-heart"></i>{% endif %}</a></div>
	</div>
	<!-- Ratings-->
	<div class="product-ratings">
		<div class="container d-flex align-items-center justify-content-between">
		<div class="ratings">
			{% if reviews|length == 0 %}
			<i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i>
			{% else %}
				{% for _ in filled_stars %}
				<i class="lni lni-star-filled m-0"></i>
				{% endfor %}
				{% for _ in unfilled_stars %}
				<i class="lni lni-star m-0"></i>
				{% endfor %}
			{% endif %}
			<span class="pl-1">{{ reviews|length }} رتبه</span>
		</div>
		<div class="total-result-of-ratings"><span>{{ reviews_avg }}</span>
			{% if reviews|length == 0 %}
			<span>بدون امتیاز</span>
			{% elif reviews_avg <= 1 %}
			<span>خیلی بد</span>
			{% elif 1 < reviews_avg <= 2 %}
			<span>بد</span>
			{% elif 2 < reviews_avg <= 3 %}
			<span>خوب</span>
			{% elif 3 < reviews_avg <= 4 %}
			<span>خیلی خوب</span>
			{% elif reviews_avg > 4 %}
			<span>عالی</span>
			{% endif %}
		</div>
		</div>
	</div>
	</div>
	{% comment %} <!-- Flash Sale Panel-->
	<div class="flash-sale-panel bg-white mb-3 py-3">
	<div class="container">
		<!-- Sales Offer Content-->
		<div class="sales-offer-content d-flex align-items-end justify-content-between">
		<!-- Sales End-->
		<div class="sales-end">
			<p class="mb-1 font-weight-bold"><i class="lni lni-bolt"></i> فروش فلش به پایان رسید</p>
			<!-- Please use event time this format: YYYY/MM/DD hh:mm:ss-->
			<ul class="sales-end-timer pl-0 d-flex align-items-center" data-countdown="2022/01/01 14:21:37">
			<li><span class="seconds">0</span> ثانیه</li>
			<li><span class="hours">0</span> ساعت</li>
			<li><span class="minutes">0</span> دقیه</li>
			<li><span class="days">0</span> روز</li>
			</ul>
		</div>
		<!-- Sales Volume-->
		<div class="sales-volume text-left">
			<p class="mb-1 font-weight-bold">82٪ فروخته شده</p>
			<div class="progress" style="height: 6px;">
			<div class="progress-bar bg-warning" role="progressbar" style="width: 82%;" aria-valuenow="82" aria-valuemin="0" aria-valuemax="100"></div>
			</div>
		</div>
		</div>
	</div>
	</div>
	<!-- Selection Panel-->
	<div class="selection-panel bg-white mb-3 py-3">
		<div class="container d-flex align-items-center justify-content-between">
			<!-- Choose Color-->
			<div class="choose-color-wrapper">
			<p class="mb-1 font-weight-bold">رنگ</p>
			<div class="choose-color-radio d-flex align-items-center">
				<!-- Single Radio Input-->
				<div class="form-check mb-0">
				<input class="form-check-input blue" id="colorRadio1" type="radio" name="colorRadio" checked="">
				<label class="form-check-label" for="colorRadio1"></label>
				</div>
				<!-- Single Radio Input-->
				<div class="form-check mb-0">
				<input class="form-check-input yellow" id="colorRadio2" type="radio" name="colorRadio">
				<label class="form-check-label" for="colorRadio2"></label>
				</div>
				<!-- Single Radio Input-->
				<div class="form-check mb-0">
				<input class="form-check-input green" id="colorRadio3" type="radio" name="colorRadio">
				<label class="form-check-label" for="colorRadio3"></label>
				</div>
				<!-- Single Radio Input-->
				<div class="form-check mb-0">
				<input class="form-check-input purple" id="colorRadio4" type="radio" name="colorRadio">
				<label class="form-check-label" for="colorRadio4"></label>
				</div>
			</div>
			</div>
			<!-- Choose Size-->
			<div class="choose-size-wrapper text-left">
			<p class="mb-1 font-weight-bold">اندازه</p>
			<div class="choose-size-radio d-flex align-items-center">
				<!-- Single Radio Input-->
				<div class="form-check mb-0 mr-2">
				<input class="form-check-input" id="sizeRadio1" type="radio" name="sizeRadio">
				<label class="form-check-label" for="sizeRadio1">س</label>
				</div>
				<!-- Single Radio Input-->
				<div class="form-check mb-0 mr-2">
				<input class="form-check-input" id="sizeRadio2" type="radio" name="sizeRadio" checked="">
				<label class="form-check-label" for="sizeRadio2">م</label>
				</div>
				<!-- Single Radio Input-->
				<div class="form-check mb-0">
				<input class="form-check-input" id="sizeRadio3" type="radio" name="sizeRadio">
				<label class="form-check-label" for="sizeRadio3">ل</label>
				</div>
			</div>
			</div>
		</div>
	</div> {% endcomment %}
	<!-- Add To Cart-->
	<div class="cart-form-wrapper bg-white mb-3 py-3">
		<div class="container">
			<!-- Add To Cart-->
			<form class="cart-form" action="{% url 'cart:cart_add' product.id %}" method="post">
				<div class="order-plus-minus d-flex align-items-center">
					<div class="quantity-button-handler">-</div>
					{{ cart_product_form.quantity }}
					{{ cart_product_form.override }}
					<div class="quantity-button-handler">+</div>
				</div>
				{% csrf_token %}
				<button class="btn btn-danger ml-3" type="submit">افزودن به سبد خرید</button>
			</form>
		</div>
		
	</div>
	<!-- Product Specification-->
	<div class="p-specification bg-white mb-3 py-3">
	<div class="container">
		<h6>مشخصات فنی</h6>
		<p class="mb-0">{{ product.description }}</p>
	</div>
	</div>
	<!-- Rating & Review Wrapper-->
	<div class="rating-and-review-wrapper bg-white py-3 mb-3">
	<div class="container">
		<h6>رتبه بندی‌ها و دیدگاه‌ها</h6>
		<div class="rating-review-content">
		{% if reviews %}
		<ul class="pl-0">
			{% for review in reviews %}
			<li class="single-user-review d-flex">
				<div class="user-thumbnail"><img src="{% if review.user.avatar %} {{ review.user.avatar.url }} {% else %} {% static 'front/img/user-profile.png' %} {% endif %}" alt=""></div>
				<div class="rating-comment">
					<div class="rating">
						{% for x in ""|ljust:review.rate %}
						<i class="lni lni-star-filled m-0"></i>
						{% endfor %}
						{% with unfilled_stars=review.rate|minus:"5"  %}
							{% for x in ""|ljust:unfilled_stars %}
							<i class="lni lni-star m-0"></i>
							{% endfor %}
						{% endwith %}
					</div>
					<p class="comment mb-0">{{ review.comment }}</p><span class="name-date">{{ review.user.full_name }} {{ review.create_at|to_jalali:'%d %B %Y' }}</span>
				</div>
			</li>
			{% endfor %}
		</ul>
		{% else %}
		<div class="text-center">
			<div>برای این محصول دیدگاهی ثبت نشده است.</div>
		</div>
		{% endif %}
		</div>
	</div>
	</div>
	<!-- Ratings Submit Form-->
	<div class="ratings-submit-form bg-white py-3">
	<div class="container">
		{% if user.is_authenticated %}
		<h6>ارسال دیدگاه</h6>
		<form action="{% url 'reviews:create_review' product.id %}" method="post">
		<div class="stars mb-3">
			<input class="star-1" value="1" type="radio" name="rate" id="star1">
			<label class="star-1" for="star1"></label>
			<input class="star-2" value="2" type="radio" name="rate" id="star2">
			<label class="star-2" for="star2"></label>
			<input class="star-3" value="3" type="radio" name="rate" id="star3">
			<label class="star-3" for="star3"></label>
			<input class="star-4" value="4" type="radio" name="rate" id="star4">
			<label class="star-4" for="star4"></label>
			<input class="star-5" value="5" type="radio" name="rate" id="star5">
			<label class="star-5" for="star5"></label><span></span>
		</div>
		{{ review_form.comment }}
		{% csrf_token %}
		<button class="btn btn-sm btn-primary" type="submit">ثبت دیدگاه</button>
		</form>
		{% else %}
		<h6>ارسال دیدگاه</h6>
		<div class="text-center">
			<div>برای ثبت دیدگاه ابتدا باید وارد حساب کاربری خود شوید</div>
			<div class="m-2">
			  <a class="btn btn-primary m-1" href="{% url 'accounts:login' %}" title="ورود به حساب کاربری" target="_blank">ورود</a>
			  <a class="btn btn-secondary " href="{% url 'accounts:signup' %}" title="عضویت در سایت" target="_blank">ثبت نام</a>
			</div>
		</div>
		{% endif %}
	</div>
	</div>
</div>
</div>
{% endblock content %}