volumes/app/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_view
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("profile/edit/avatar/", views.change_avatar, name="change_avatar"),
    path('profile/wishlist/', views.user_wishlist, name="user_wishlist"),
    path("profile/wishlist/add_remove_product/<int:id>/",
         views.add_remove_wishlist,
         name="add_remove_wishlist"),

    # default django url view
    path("login/", auth_view.LoginView.as_view(
            template_name="accounts/login.html"), name="login"),
    path("logout/", auth_view.LogoutView.as_view(), name="logout"),
    path(
        "password_change/", auth_view.PasswordChangeView.as_view(
            template_name="accounts/password_change_form.html"),
        name="password_change"),
    path(
        "password_change/done/",
        auth_view.PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "password_reset/", auth_view.PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="registration/password_reset_subject.txt",
            success_url=reverse_lazy("accounts:password_reset_done")),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_view.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_view.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete")),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_view.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

volumes/app/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name="cart_detail"),
    path('add/<int:product_id>/', views.cart_add, name="cart_add"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
]

volumes/app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dj_rest_auth.views import PasswordResetConfirmView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    # API urls
    # authentication
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/auth/', include('accounts.api_urls', namespace='api-auth')),
    path('api/v1/auth/password/reset/confirm/<uibd64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    # other app
    path('api/v1/shop/', include('shop.api_urls', namespace='api-shop')),

    # Traditional Django urls
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('cart/', include("cart.urls", namespace="cart")),
    path('orders/', include("orders.urls", namespace="orders")),
    path('coupons/', include("coupons.urls", namespace="coupons")),
    path('payments/', include("payments.urls", namespace="payments")),
    path('reviews/', include("reviews.urls", namespace="reviews")),
    path('', include("shop.urls", namespace="shop")),
]
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)


# API Schema
urlpatterns += [
    # YOUR PATTERNS
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/v1/swagger/',
         SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/v1/schema/redoc/',
         SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

volumes/app/coupons/urls.py
from django.urls import path
from . import views

app_name = "coupons"

urlpatterns = [
    path("apply/", views.coupon_apply, name="apply"),
]

volumes/app/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("", views.orders_list, name="orders_list"),
    path("create/", views.order_create, name="order_create"),
    path("<int:id>/", views.order_detail, name="order_detail"),
    path("<int:order_id>/payment/", views.send_to_payment,
         name="order_payment")
]

volumes/app/shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.index, name="index"),
    path("shop/", views.product_list, name="product_list"),
    path("category/<slug:category_slug>/", views.product_list,
         name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail,
         name="product_detail"),
]

volumes/app/cart/models.py
from django.db import models

# Create your models here.

volumes/app/cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    """
    Form used for adding a product to the cart.

    This form provides fields for specifying the quantity of the product to
    be added, as well as an optional field to override the quantity if needed.
    """
    quantity = forms.IntegerField(
        initial=1,
        min_value=1,
        label="",
        widget=forms.widgets.NumberInput(
            attrs={
                "class": "form-control cart-quantity-input",
                "step": "1", }
        ),
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

volumes/app/cart/views.py
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from django.http import Http404
from django.views.decorators.http import require_POST
from shop.models import Product
from coupons.forms import CouponApplyForm
from cart.cart import Cart
from cart.forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    """
    Add a product to the cart.

    This view function handles the POST request to add a product to the cart.
    It retrieves the product based on the provided product ID, validates the
    form data submitted by the user, and adds the product to the cart with the
    specified quantity. After adding the product, the user is redirected to
    the cart detail page.

    Args:
        request: The HTTP request object.
        product_id: The ID of the product to be added to the cart.

    Returns:
        Redirects to the cart detail page.

    Raises:
        Http404: If the product with the specified ID does not exist.
    """
    cart = Cart(request)
    try:
        product = get_object_or_404(Product, id=product_id)
    except Http404:
        return render(request, "404.html", status=404)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd["quantity"],
                 override_quantity=cd["override"])
    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
    """
    Remove a product from the cart.

    This view function handles the POST request to remove a product from the
    cart. It retrieves the product based on the provided product ID and
    removes it from the cart. After removing the product, the user is
    redirected to the cart detail page.

    Args:
        request: The HTTP request object.
        product_id: The ID of the product to be removed from the cart.

    Returns:
        Redirects to the cart detail page.

    Raises:
        Http404: If the product with the specified ID does not exist.
    """
    cart = Cart(request)
    try:
        product = get_object_or_404(Product, id=product_id)
    except Http404:
        return render(request, "404.html", status=404)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    """
    Display the cart detail page.

    This view function renders the cart detail page, which shows the products
    currently in the cart. It retrieves the cart object from the request, adds
    the update quantity form for each item in the cart, and includes the
    coupon apply form. The rendered page includes the cart information and
    forms for updating quantities and applying coupons.

    Args:
        request: The HTTP request object.

    Returns:
        The rendered cart detail page.
    """
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(initial={
            "quantity": item["quantity"],
            "override": True, },
            auto_id=False,)

    coupon_apply_form = CouponApplyForm()

    return render(request,
                  "cart/detail.html",
                  {"cart": cart,
                   "coupon_apply_form": coupon_apply_form})

volumes/app/cart/templates/cart/detail.html
{% extends 'shop/shop-base.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}

{% block title %}
{% block header-title %}
سبد خرید من
{% endblock header-title %}
{% endblock title %}


{% block back-button %}
<div class="back-button"><a href="{% url 'shop:product_list' %}"><i class="lni lni-arrow-right"></i></a></div>
{% endblock back-button %}


{% block content %}
<div class="page-content-wrapper">
	<div class="container">
	<!-- Cart Wrapper-->
	{% if cart %}
	<div class="cart-wrapper-area py-3">
		<div class="cart-table card mb-3">
		<div class="table-responsive card-body">
			<table class="table mb-0">
			<tbody>
				{% for item in cart %}
					{% with item.product as product %}
						<!-- single item in the cart -->
						<tr>
							<th scope="row">
								<form action="{% url 'cart:cart_remove' product.id %}" id="{{ product.id }}" method="post">
									<a class="remove-product" href="#" onclick="document.getElementById('{{ product.id }}').submit()"><i class="lni lni-close"></i></a>
									{% csrf_token %}
								</form>
							</th>
							<td><img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'front/img/nopic.jpg' %} {% endif %}" alt=""></td>
							<td><a href="{{ product.get_absolute_url }}"> {{product.name}}    <span>{{ item.price|floatformat:-2|intcomma }} تومان ×  {{ item.quantity }} </span> </a> </td>
							<td>
								<div class="quantity">
									<form class="cart-form" action="{% url 'cart:cart_add' product.id %}" method="post">
									  <div class="order-plus-minus d-flex align-items-center">
										<div class="quantity-button-handler">-</div>
										{{ item.update_quantity_form.quantity|add_class:"qty-text" }}
										{{ item.update_quantity_form.override }}
										<div class="quantity-button-handler">+</div>
									  </div>
									  {% csrf_token %}
									  <button class="btn btn-danger ml-3" type="submit">بروزرسانی</button>
									</form>
								</div>
							</td>
							<td><span class="font-weight-bold text-body h5">{{ item.total_price|floatformat:-2|intcomma }} تومان</span></td>
						</tr>
					{% endwith %}
				{% endfor %}		
			</tbody>
			</table>
		</div>
		</div>
		<!-- Coupon Area-->
		<div class="card coupon-card mb-3">
		<div class="card-body">
			
			<div class="apply-coupon">
				{% if not cart.coupon_id and request.session.coupon_code %}
				<div class="alert alert-warning" role="alert">
					<button type="button" class="close mr-2" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<p class="d-inline">کد تخفیف "{{ request.session.coupon_code }}" وجود ندارد!</p>
				</div>
				{% elif cart.coupon_id and request.session.coupon_code %}
				<div class="alert alert-success" role="alert">
					<button type="button" class="close mr-2" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<p class="d-inline">کد تخفیف "{{ request.session.coupon_code }}" با موفقیت وارد شد!</p>
				</div>
				{% endif %}
			<h6 class="mb-0">تخفیف دارید؟</h6>
			<p class="mb-2">کد تخفیف خود را اینجا وارد کنید و از تخفیف های عالی استفاده کنید!</p>
			<!-- for cart with coupon to remove coupon-->
			{% if cart.coupon %}
			<div class="coupon-form">
				<form action="{% url 'coupons:apply' %}" method="get">
					<input class="form-control" type="text" value="{{cart.coupon}}" disabled>
					{% csrf_token %}
					<button class="btn btn-danger" type="submit">حذف کوپن</button>
				</form>
			</div>
			{% else %}
			<!-- for cart without coupon to add coupon -->
			<div class="coupon-form">
				<form action="{% url 'coupons:apply' %}" method="post" aria-disabled="true">
					{% render_field coupon_apply_form.code class+="form-control" placeholder="SUHA30" %}
					{% csrf_token %}
					<button class="btn btn-primary" type="submit">درخواست دادن</button>
				</form>
			</div>
			{% endif %}
			</div>
		</div>
		</div>
		<!-- Cart Amount Area-->
		<div class="card cart-amount-area">
		<div class="card-body d-flex align-items-center justify-content-between">
			{% if cart.coupon %}
			<div class="d-flex justify-content-between align-items-center">
				<h5 class="total-price mb-0 mr-3"><span class="counter">{{ cart.get_total_price_after_discount|floatformat:-2|intcomma }}</span>تومان</h5>
				<h6 class="total-price mb-0 text-decoration-line-through text-danger"><span class="counter">{{ cart.get_total_price|floatformat:-2|intcomma }}</span>تومان </h6>
			</div>
			<a class="btn btn-warning" href="{% url 'orders:order_create' %}">پرداخت </a>
			{% else %}
				<h5 class="total-price mb-0 h4 font-weight-bold"><span class="counter">{{ cart.get_total_price|floatformat:-2|intcomma }}</span> تومان</h5><a class="btn btn-warning" href="{% url 'orders:order_create' %}">پرداخت </a>
			{% endif %}
		</div>
		</div>
	</div>
	{% else %}
	<div class="cart-empty">
		<div class="row">
			<div class="col-12">
				<div class="empty">
					<span class="pic">
						<img src="{% static 'front/img/cart/empty-cart.png' %}" alt="">
					</span>
					<h3>
						سبد خرید شما خالی است
					</h3>
					<ul class="menu">
						<li class="item">
							<a href="/">
								صفحه اصلی
							</a>
						</li>
						<li class="item">
							<a href="{% url 'accounts:profile' %}">
								حساب کاربری
							</a>
						</li>
						<li class="item">
							<a href="/">
								فروشگاه
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	{% endif %}
	</div>
</div>
{% endblock content %}


{% block domready %}
<script>
	var form = document.getElementById("remove-product-form");

	document.getElementById("remove-product-submit").addEventListener("click", function () {
		form.submit();
	});
</script>
{% endblock domready %}